#cargo-features = ["edition"]

[package]
name = "rustql-extractor"
version = "0.1.0"
authors = ["Nicolas Winkler <niwinkle@student.ethz.ch>"]
edition = "2018"

[dependencies]
serde = "*"
serde_json = "*"
bincode = "*"
serde_derive = "*"

[dependencies.rustql-common]
path = "../rustql-common"

