[package]
name = "rustql-linker"
version = "0.1.0"
authors = ["Nicolas Winkler <nicolas.winkler@gmx.ch>"]
edition = "2018"

[dependencies]
datafrog = "0.1.0"
serde = "*"
serde_json = "*"
bincode = "*"

[dependencies.rustql-common]
path = "../rustql-common"
